force-app/main/default/objects/Lead/fields/S4SSDR_Processed__c.field-meta.xml
<CustomField>
    <fullName>S4SSDR_Processed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>SDR Processed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/S4SSDR_Status__c.field-meta.xml
<CustomField>
    <fullName>S4SSDR_Status__c</fullName>
    <label>SDR Lead Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Contacted</fullName>
            </value>
            <value>
                <fullName>Responded</fullName>
            </value>
            <value>
                <fullName>LastNudge</fullName>
                <label>Last Nudge</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/S4S_SDR_Lead_Status.cls
//*************************************************************************************************************************************
//@ Description : SDR Agent Function to update the Lead Status
//@ Author      : Christoffel Smeets (ksmeets@salesforce.com)          
//@ Date        : 17 March 2025        
//@ Test Class  : S4S_SDR_Lead_StatusTest
//**************************************************************************************************************************************


public with sharing class S4S_SDR_Lead_Status {
    private static Map<string,string> statusMap = new Map<string,string>{
        'CONTACTED'=>'Contacted',
        'RESPONDED'=>'Responded',
        'REJECTED'=>'Rejected',
        'LASTNUDGE'=>'LastNudge',
        'QUALIFIED'=>'Qualified'
    };
    private static List<String> proccesedStatus = new List<String>{'REJECTED', 'LASTNUDGE', 'QUALIFIED'};

    @InvocableMethod
    public static List<Response> updateLeadStatus(List<Request> requests) {
        Request input = requests[0];
        List<Response> responses = new List<Response>();
        Response output = new Response();

        String status = input.status.toUpperCase();
        status = status.trim();
        status = status.remove('.');

        if (statusMap.containsKey(status)) {
            input.lead.S4SSDR_Status__c = statusMap.get(status);
        }

        if (proccesedStatus.contains(status)) {
            
            Database.DMLOptions dmo = new Database.DMLOptions();
            dmo.assignmentRuleHeader.useDefaultRule = true;
            input.lead.setOptions(dmo);

            input.lead.S4SSDR_Processed__c = true;

        }
 
        Database.SaveResult sr = Database.update (input.lead);
        output.success =  sr.isSuccess();

        responses.add(output);
        return responses;
    }

    public class Request {
        @InvocableVariable(required=true)
        public Lead lead;
        @InvocableVariable(required=true)
        public string status;    
    }

    public class Response {
        @InvocableVariable
        public boolean success;
    }
}